# Generated by Django 5.1 on 2024-08-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_turnotrabalho_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnotrabalho',
            name='cooperado',
        ),
        migrations.RemoveField(
            model_name='turnotrabalho',
            name='locacao',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='TurnoTrabalho',
        ),
    ]
