# Generated by Django 5.1 on 2024-08-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_turnotrabalho_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnotrabalho',
            name='horas_trabalhadas',
        ),
    ]
