# Generated by Django 5.1 on 2024-08-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_remove_turnotrabalho_horas_trabalhadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnotrabalho',
            name='valor_por_hora',
        ),
        migrations.AddField(
            model_name='turnotrabalho',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coop.categorias'),
        ),
    ]
