# Generated by Django 5.1 on 2024-08-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_remove_turnotrabalho_valor_por_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnotrabalho',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coop.categorias'),
        ),
    ]
